version: '3'
services:
  ftp-basestation:
    image: fauria/vsftpd
    container_name: ftp-server
    environment:
      FTP_USER: nybsys
      FTP_PASS: 12345
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
